"""TransE negative-sampling SGD training loop.

Separated from EdgeEmbeddingService so that the 190-line training loop doesn't
crowd the core embedding read/write/predict API.  The trainer operates on the
same ``rel_emb`` dict that EdgeEmbeddingService caches in memory — mutations
are reflected back to the caller because Python dicts are passed by reference.

Usage (via EdgeEmbeddingService.train() — prefer that interface)::

    from graphrag.graph.transx_trainer import TransXTrainer

    trainer = TransXTrainer(neo4j_client, rel_emb=svc._rel_emb, embed_dim=768)
    summary = await trainer.train(tenant="acme", epochs=100)
    # svc._rel_emb is now updated with learned relation embeddings
"""

from __future__ import annotations

import math
import random

import structlog

log = structlog.get_logger(__name__)


class TransXTrainer:
    """
    Train TransE relation embeddings using negative-sampling SGD.

    Positive triples come from RELATES_TO edges in Neo4j.
    Negative triples are generated by corrupting the head or tail entity
    with a randomly sampled entity from the same tenant.

    Only relation embeddings are updated — entity embeddings remain fixed
    (they are pre-computed by the sentence transformer).  Updated embeddings
    are L2-normalised after each epoch and stored back to Neo4j.

    Parameters
    ----------
    neo4j_client :
        Live Neo4j client for loading triples and persisting results.
    rel_emb :
        The relation-embedding cache dict from EdgeEmbeddingService.  Mutations
        here are reflected back to the service (shared reference).
    embed_dim :
        Embedding dimension; must match entity embeddings.
    """

    def __init__(self, neo4j_client, rel_emb: dict[str, list[float]], embed_dim: int):
        self._neo4j    = neo4j_client
        self._rel_emb  = rel_emb   # shared reference — mutations are visible to caller
        self._embed_dim = embed_dim

    # ── TransE scoring helpers ─────────────────────────────────────────────────

    def _score(
        self,
        head: list[float],
        r_vec: list[float],
        tail: list[float],
    ) -> float:
        """‖ h + r - t ‖₂ — lower = more plausible triple."""
        dim  = len(r_vec)
        diff = [head[i] + r_vec[i] - tail[i] for i in range(dim)]
        return math.sqrt(sum(x * x for x in diff))

    # ── Training loop ──────────────────────────────────────────────────────────

    async def train(
        self,
        tenant: str = "default",
        epochs: int = 100,
        lr: float = 0.01,
        margin: float = 1.0,
        neg_samples: int = 5,
        batch_size: int = 256,
        seed: int = 42,
    ) -> dict:
        """
        Run the SGD training loop and persist learned embeddings to Neo4j.

        Returns a training summary dict with ``triples``, ``epochs``,
        ``final_loss``, ``loss_curve``, and ``relations_updated``.
        """
        rng = random.Random(seed)

        # ── Load positive triples ──────────────────────────────────────────
        log.info("transx_train.loading_triples", tenant=tenant)
        triple_rows = await self._neo4j.run(
            """
            MATCH (s:Entity {tenant: $tenant})-[r:RELATES_TO]->(t:Entity {tenant: $tenant})
            WHERE s.embedding IS NOT NULL AND size(s.embedding) > 0
              AND t.embedding IS NOT NULL AND size(t.embedding) > 0
            RETURN s.embedding AS head_emb,
                   r.relation  AS relation,
                   t.embedding AS tail_emb
            LIMIT 50000
            """,
            tenant=tenant,
        )
        if not triple_rows:
            log.warning("transx_train.no_triples", tenant=tenant)
            return {"epochs": 0, "triples": 0, "error": "no_triples_found"}

        # Collect unique entity embeddings for negative sampling
        entity_rows = await self._neo4j.run(
            """
            MATCH (e:Entity {tenant: $tenant})
            WHERE e.embedding IS NOT NULL AND size(e.embedding) > 0
            RETURN e.embedding AS embedding
            LIMIT 10000
            """,
            tenant=tenant,
        )
        entity_embs = [list(r["embedding"]) for r in entity_rows]
        if len(entity_embs) < 2:
            return {"epochs": 0, "triples": 0, "error": "too_few_entities"}

        triples: list[tuple[list[float], str, list[float]]] = [
            (list(r["head_emb"]), r["relation"], list(r["tail_emb"]))
            for r in triple_rows
        ]
        n_triples = len(triples)
        log.info(
            "transx_train.start",
            triples=n_triples,
            entities=len(entity_embs),
            epochs=epochs,
            lr=lr,
            margin=margin,
        )

        # Ensure relation embeddings are loaded into the shared cache
        unique_rels = {rel for _, rel, _ in triples}
        for rel in unique_rels:
            if rel.upper() not in self._rel_emb:
                # Derive deterministically if not already cached
                import hashlib
                seed_val = int(hashlib.sha256(rel.upper().encode()).hexdigest(), 16) % (2 ** 32)
                r_rng = random.Random(seed_val)
                raw   = [r_rng.gauss(0.0, 1.0) for _ in range(self._embed_dim)]
                norm  = math.sqrt(sum(x * x for x in raw)) or 1.0
                self._rel_emb[rel.upper()] = [x / norm for x in raw]

        # ── Epoch loop ────────────────────────────────────────────────────
        epoch_losses: list[float] = []

        for epoch in range(epochs):
            rng.shuffle(triples)
            epoch_loss = 0.0
            n_updates  = 0

            for batch_start in range(0, n_triples, batch_size):
                batch = triples[batch_start: batch_start + batch_size]

                rel_grad: dict[str, list[float]] = {}
                rel_count: dict[str, int] = {}

                for head, rel, tail in batch:
                    r_vec = self._rel_emb[rel.upper()]
                    d_pos = self._score(head, r_vec, tail) + 1e-8

                    for _ in range(neg_samples):
                        if rng.random() < 0.5:
                            neg_head, neg_tail = rng.choice(entity_embs), tail
                        else:
                            neg_head, neg_tail = head, rng.choice(entity_embs)

                        d_neg = self._score(neg_head, r_vec, neg_tail) + 1e-8
                        loss  = max(0.0, margin + d_pos - d_neg)
                        if loss <= 0.0:
                            continue

                        epoch_loss += loss
                        n_updates  += 1

                        dim = len(r_vec)
                        pos_diff = [head[i] + r_vec[i] - tail[i] for i in range(dim)]
                        neg_diff = [neg_head[i] + r_vec[i] - neg_tail[i] for i in range(dim)]
                        grad = [pos_diff[i] / d_pos - neg_diff[i] / d_neg for i in range(dim)]

                        rel_key = rel.upper()
                        if rel_key not in rel_grad:
                            rel_grad[rel_key]  = [0.0] * dim
                            rel_count[rel_key] = 0
                        for i in range(dim):
                            rel_grad[rel_key][i] += grad[i]
                        rel_count[rel_key] += 1

                for rel_key, grad_acc in rel_grad.items():
                    n = rel_count[rel_key] or 1
                    r_vec   = self._rel_emb[rel_key]
                    dim     = len(r_vec)
                    updated = [r_vec[i] - lr * (grad_acc[i] / n) for i in range(dim)]
                    norm    = math.sqrt(sum(x * x for x in updated)) or 1.0
                    self._rel_emb[rel_key] = [x / norm for x in updated]

            avg_loss = epoch_loss / max(n_updates, 1)
            epoch_losses.append(avg_loss)

            if (epoch + 1) % 10 == 0 or epoch == epochs - 1:
                log.info(
                    "transx_train.epoch",
                    epoch=epoch + 1,
                    avg_loss=round(avg_loss, 5),
                    n_updates=n_updates,
                )

        # ── Persist learned embeddings ─────────────────────────────────────
        stored = 0
        for rel_key, emb in self._rel_emb.items():
            await self._neo4j.run(
                """
                MERGE (re:RelationEmbedding {relation: $rel})
                SET re.embedding   = $embedding,
                    re.embed_dim   = $dim,
                    re.source      = 'trained',
                    re.updated_at  = datetime()
                """,
                rel=rel_key,
                embedding=emb,
                dim=self._embed_dim,
            )
            stored += 1

        summary = {
            "triples":           n_triples,
            "entities":          len(entity_embs),
            "epochs":            epochs,
            "final_loss":        round(epoch_losses[-1], 5) if epoch_losses else 0,
            "loss_curve":        [round(l, 5) for l in epoch_losses[::max(1, epochs // 20)]],
            "relations_updated": stored,
        }
        log.info("transx_train.complete", **summary)
        return summary
