apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: graphrag
resources:
  - namespace.yaml
  - configmap.yaml
  - energy-published-rdf-pvc.yaml
  - service-account.yaml
  - api.yaml
  - mcp.yaml
  - workers.yaml
  - network-policy.yaml
